# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
     - master/*

variables:
- group: storageInfo
- name: storageSAS
  value: 'My STorage'


pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo $(storageContainer)
    echo $(storageAccount)
  displayName: 'Run a multi-line script'
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    connectedServiceNameARM : $(serviceConnectionName)
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: | 
      mkdir $(Build.SourcesDirectory)\unzipped
      az storage blob download --container-name $(storageContainer) --file $(Build.SourcesDirectory)/$(zipfileName) --name $(zipfileName) --sas-token '$(sasTokenZip)' --account-name $(storageAccount)
      unzip -l $(Build.SourcesDirectory)/$(zipfileName) 
      unzip $(Build.SourcesDirectory)/$(zipfileName)  –d $(Build.SourcesDirectory)/unzipped
      ls -lR $(Build.SourcesDirectory)/unzipped
