# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
     - master/*

variables:
- group: storageInfo
- name: storageSAS
  value: 'My STorage'


pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo $(storageContainer)
    echo $(storageAccount)
  displayName: 'Run a multi-line script'
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    connectedServiceNameARM : $(serviceConnectionName)
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: | 
      mkdir $(Build.SourcesDirectory)\BlobFile
      az storage blob download --container-name $(storageContainer) --file $(Build.SourcesDirectory)\$(zipfileName) --name "testfile.tar" --sas-token '$(sasToken)' --account-name $(storageAccount)
      tar -xvf $(Build.SourcesDirectory)\$(zipfileName) -C $(Build.SourcesDirectory)\
