# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
     - master/*

variables:
- group: storageInfo
- name: storageSAS
  value: 'My STorage'


pool:
  vmImage: 'ubuntu-latest'

steps:

- task: CmdLine@2
  inputs:
    script: 'echo externalVariable $(externalVariable)' 

- task: AzureCLI@2
  enabled : false
  inputs:
    azureSubscription: $(azureSubscription)
    connectedServiceNameARM : $(serviceConnectionName)
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: | 
      echo "Echo externalVariable $(externalVariable)"
     
