# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
     - master/*

variables:
- group: storageInfo
- name: storageSAS
  value: 'My STorage'


pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo $(storageContainer)
    echo $(storageAccount)
  displayName: 'Run a multi-line script'


- task: DownloadPackage@1
  continueOnError: false  
  inputs:
    packageType: 'maven'
    feed: $(feedId) # if scoped to project <projectId>/<feedId> else just <feedId>
    definition: $(packageName)
    version: '1.0.0-snapshot' # Should be normalized version
    files: '*.war'
    downloadPath: '$(Build.SourcesDirectory)'

- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    connectedServiceNameARM : $(serviceConnectionName)
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: | 
      az storage blob download --container-name $(storageContainer) --file $(Build.SourcesDirectory)/$(zipfileName) --name $(zipfileName) --sas-token '$(sasTokenZip)' --account-name $(storageAccount)
      unzip -l $(Build.SourcesDirectory)/$(zipfileName)
      unzip $(Build.SourcesDirectory)/$(zipfileName) 
      ls -l

